# Data Transformation

## Removing Duplicates

In [1]:
import numpy as np
import pandas as pd
from numpy import nan as NA

In [2]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})

In [4]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [6]:
data.duplicated() # Returns True if duplicate values found.

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [8]:
data.drop_duplicates() # it will drops the duplicate data with their index as well as values.

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [9]:
data['v1'] = range(7)

In [10]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [11]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [12]:
data.drop_duplicates(['k1', 'k2'], keep='last') # refer book to understand or see indexes.

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Transforming Data Using a Function or Mapping

In [13]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'], 
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [14]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [29]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [30]:
lowercased = data['food'].str.lower()

In [31]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [32]:
data['animal'] = lowercased.map(meat_to_animal)

In [33]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [34]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

## Replacing Values

In [2]:
data = pd.Series([1., -999., 2., -999, -1000., 3.]) # -999. is a sentinel for missing data.

In [3]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [9]:
data.replace(-999., np.nan) # we use replace function to replace -999. to NaN.

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [11]:
data.replace([-999., -1000.], np.nan) # replacing multiple values by passing a list.

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [13]:
data.replace({-999.: np.nan, -1000.: 0}) # we can replace values using dictionary also.

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## Renaming Axis Indexing

In [14]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                    index=['Ohio', 'Colorado', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])

In [15]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [17]:
transform = lambda x: x[:4].upper() # creating a anonymous function to transform axis.

In [18]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [27]:
data.index = data.index.map(transform) # assigning new indexes permanently.

In [28]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [29]:
data.rename(index=str.title, columns=str.upper) # renaming without touching the original.

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [32]:
data.rename(index={'OHIO':'INDIANA'},
           columns={'three':'pikaboo'}) # changing indexes and columns with rename function.

one  two  pikaboo  four
INDIANA    0    1        2     3
COLO       4    5        6     7
NEW        8    9       10    11

In [37]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [38]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

## Discretization and Binning

In [39]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [40]:
bins = [18, 25, 35, 60, 100]

In [41]:
cats = pd.cut(ages, bins)

In [42]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [44]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [45]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [48]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [49]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [50]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [52]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [53]:
data = np.random.rand(20)

In [54]:
data

array([0.21521849, 0.77235544, 0.07436551, 0.53760688, 0.77327358,
       0.88879537, 0.1495218 , 0.09576878, 0.44817088, 0.9773774 ,
       0.50867407, 0.26865711, 0.6873588 , 0.19743979, 0.53747308,
       0.20123675, 0.74922249, 0.33671289, 0.28015721, 0.58287999])

In [55]:
pd.cut(data, 4, precision=2)

[(0.073, 0.3], (0.75, 0.98], (0.073, 0.3], (0.53, 0.75], (0.75, 0.98], ..., (0.073, 0.3], (0.53, 0.75], (0.3, 0.53], (0.073, 0.3], (0.53, 0.75]]
Length: 20
Categories (4, interval[float64]): [(0.073, 0.3] < (0.3, 0.53] < (0.53, 0.75] < (0.75, 0.98]]

In [56]:
data = np.random.rand(1000)

In [71]:
data

array([8.56047967e-01, 9.53926787e-01, 5.56366987e-01, 2.73550496e-02,
       4.20852927e-01, 6.80652846e-01, 7.37158823e-01, 8.33352845e-01,
       1.19236474e-01, 7.03572433e-01, 7.54293317e-01, 9.36458165e-01,
       8.62839201e-02, 5.64171076e-01, 2.61214550e-01, 9.55564969e-01,
       9.40305088e-01, 5.06272107e-01, 9.53555237e-01, 5.08595350e-01,
       7.46671696e-01, 8.02966365e-01, 4.41659080e-01, 9.17778211e-01,
       8.76671356e-01, 2.74668601e-01, 6.90532947e-01, 7.92115929e-01,
       9.65670770e-01, 6.94418617e-01, 2.40041559e-01, 1.78881800e-02,
       7.86778127e-01, 8.19227453e-01, 4.38746792e-01, 7.26023465e-01,
       7.12490309e-01, 8.21586365e-01, 3.46315080e-01, 5.68370740e-01,
       4.13999465e-01, 5.18449966e-01, 9.39155520e-01, 4.77386554e-01,
       9.79209017e-01, 7.19206521e-02, 7.40312642e-01, 7.45711212e-02,
       8.72369183e-01, 2.19305178e-01, 3.87745129e-01, 1.68955641e-01,
       8.18453152e-01, 6.56081533e-01, 8.14519522e-04, 8.41343147e-01,
      

In [63]:
cats = pd.qcut(data, 4, labels=['XtraSmallData', 'SmallData', 'MediumData', 'LargeData']) # Cutting long data into quartiles.

In [64]:
cats

['LargeData', 'LargeData', 'MediumData', 'XtraSmallData', 'SmallData', ..., 'XtraSmallData', 'SmallData', 'LargeData', 'SmallData', 'LargeData']
Length: 1000
Categories (4, object): ['XtraSmallData' < 'SmallData' < 'MediumData' < 'LargeData']

In [65]:
pd.value_counts(cats)

LargeData        250
MediumData       250
SmallData        250
XtraSmallData    250
dtype: int64

In [66]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.514, 0.874], (0.874, 0.998], (0.514, 0.874], (-0.0009893, 0.116], (0.116, 0.514], ..., (-0.0009893, 0.116], (0.116, 0.514], (0.514, 0.874], (0.116, 0.514], (0.514, 0.874]]
Length: 1000
Categories (4, interval[float64]): [(-0.0009893, 0.116] < (0.116, 0.514] < (0.514, 0.874] < (0.874, 0.998]]

## Detecting and Filtering Outliers

In [72]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [74]:
data.head()

0         1         2         3
0 -0.547249  1.130060 -1.047918  1.058495
1 -0.293717  0.982490 -0.388892 -1.987342
2  0.948109 -1.210503  0.388984  0.836217
3  0.301592 -0.743777  0.218649 -0.323411
4 -0.292187  0.577679  1.404455 -0.378267

In [76]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.082895     0.001420     0.027512    -0.037974
std       0.999530     1.006798     0.983391     0.966907
min      -2.879615    -3.485770    -2.833251    -3.320791
25%      -0.758924    -0.720658    -0.627004    -0.692593
50%      -0.115789     0.021513    -0.000839    -0.061307
75%       0.599454     0.679765     0.675792     0.584601
max       3.015487     3.146617     3.152173     3.689162

In [90]:
# Suppose we want to find values which is > 3 in column number 2.

In [91]:
col = data[2]

In [92]:
col[np.abs(col) > 3]

194    3.082156
325    3.152173
Name: 2, dtype: float64

In [97]:
data[np.abs(data > 3).any(1)] #selecting all rows having a values exceeding 3 or -3.

0         1         2         3
194  0.951926  0.752108  3.082156 -0.092126
325  0.638785  0.612897  3.152173  0.439690
524  3.015487  1.016344  0.145671  0.555686
556  1.210044  1.537784 -0.270861  3.689162
728  0.172473  3.146617 -0.495387  1.027042

In [98]:
data[np.abs(data > 3)] = np.sign(data) * 3

In [99]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.082910     0.001273     0.027278    -0.038663
std       0.999482     1.006350     0.982666     0.964491
min      -2.879615    -3.485770    -2.833251    -3.320791
25%      -0.758924    -0.720658    -0.627004    -0.692593
50%      -0.115789     0.021513    -0.000839    -0.061307
75%       0.599454     0.679765     0.675792     0.584601
max       3.000000     3.000000     3.000000     3.000000

In [102]:
np.sign(data).head() # 1 for positive values and -1 for negative values.

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0 -1.0  1.0  1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0  1.0  1.0 -1.0

## Permutation and Random Sampling

In [103]:
df = pd.DataFrame(np.arange(5*4).reshape((5, 4)))

In [113]:
sampler = np.random.permutation(5) # creating random axis changes using permutaion aka Kramchay.

In [114]:
sampler

array([0, 2, 3, 4, 1])

In [115]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [116]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7

In [123]:
df.sample(n=3) # display sample data with sample method of pandas we can display subset without replacement.

0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11

In [124]:
choices = pd.Series([5, 7, -1, 6, 4])

In [128]:
draws = choices.sample(n=10, replace=True)

In [129]:
draws

1    7
1    7
1    7
4    4
0    5
3    6
3    6
4    4
0    5
0    5
dtype: int64

## Computing Indicator / Dummy Variables

In [142]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b', 'd'],
                  'data1': range(7)})

In [143]:
pd.get_dummies(df['key'])

a  b  c  d
0  0  1  0  0
1  0  1  0  0
2  1  0  0  0
3  0  0  1  0
4  1  0  0  0
5  0  1  0  0
6  0  0  0  1

In [148]:
dummies = pd.get_dummies(df['key'], prefix='Dummy_Data')

In [149]:
dummies

Dummy_Data_a  Dummy_Data_b  Dummy_Data_c  Dummy_Data_d
0             0             1             0             0
1             0             1             0             0
2             1             0             0             0
3             0             0             1             0
4             1             0             0             0
5             0             1             0             0
6             0             0             0             1